add eslint, eslint-loader, fix codestyle
extg/retail pull request #1
Opened 2017-07-21 16:15 UTC by Allarepossible

2017-07-21 16:24 UTC, extg commented on .idea/jsLibraryMappings.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Это что такое!???

2017-07-21 16:36 UTC, extg requested changes

2017-07-21 16:36 UTC, extg commented on package.json
> +  "author": "Vasily Krylov <0777144@gmail.com> & leisan",
Нормально себя напиши)

2017-07-21 16:38 UTC, extg requested changes

2017-07-21 16:38 UTC, extg commented on .idea/jsLibraryMappings.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Я еще вижу это тут

2017-07-21 17:03 UTC, extg requested changes

2017-07-21 17:03 UTC, extg commented on .eslintrc
> +    "mocha": true,
У нас пока не тестов)

2017-07-21 17:03 UTC, extg commented on .eslintrc
> +    "semi": ["error", "always"],
Зачем писать точку с запятой, если можно не писать)

2017-07-21 17:36 UTC, extg requested changes
Request changes

2017-07-22 13:13 UTC, extg commented on package.json
> +  "author": "Vasily Krylov <0777144@gmail.com> & leisan",
https://docs.npmjs.com/files/package.json#people-fields-author-contributors

2017-07-23 14:58 UTC, Allarepossible commented on .eslintrc
> +    "mocha": true,
будут

2017-07-23 17:00 UTC, merged